# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hueman"
license = "MIT"
licenselink = "https://github.com/ryanemax/ryanemax.github.io"
description = "powered by https://github.com/presscustomizr/hueman"
homepage = "http://www.futurestack.cn/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "ryanemax"
  homepage = "https://github.com/ryanemax"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
