# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Base16-ryn"
license = "MIT"
licenselink = "http://htdvisser.mit-license.org/"
description = "Base16 is a colorful theme for ryn"
homepage = "https://www.futurestack.cn/"
tags = ["blog", "syntax highlighting"]
features = ["blog", "syntax highlighting"]
min_version = 0.15

[author]
  name = "Ryane Max"
  homepage = "https://github.com/ryanemax"
